export const VEHICLES_START = "VEHICLES_START"
export const VEHICLES_SUCCESS = "VEHICLES_SUCCESS"
export const VEHICLES_FAIL = "VEHICLES_FAIL"
export const VEHICLES_DISMISS_ERROR = "VEHICLES_DISMISS_ERROR"
